services:
  media_server:
    container_name: media
    image: anomot/media-server
    ports:
      - "5000:5000"
    links:
      - clamav
    environment:
      - CLAMAV_LOCATION=clamav
      - CLAMAV_PORT=3310
    depends_on:
      clamav:
        condition: service_healthy
    networks:
      - net
      - default
  clamav:
    hostname: clamav
    image: mkodockx/docker-clamav:alpine
    ports:
      - "3310:3310"
    healthcheck:
      test: [ "CMD", "./check.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s
networks:
  net:
    driver: bridge
    name: net